[package]
name = "kiko-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
kiko = { path = "../kiko", default-features = false }
tokio = { version = "1.45.0", features = ["full"] }
warp = "0.3.7"
